### ISSUE TITLE
基本想法

### ISSUE THREAD

**Issue by jwu** [fireball-x/engine-framework#1]
Engine Framework 是一个 wrapper 层. 和 0.5 版本以前的 Engine Framework 不同, 他不是一个 Entity Component 系统,  Engine Framework 扮演的是一个描述和转译 Runtime 的中间层, 以及一个驱动 Runtime 运作 (loop) 的机器.

## 我们在编写 Engine Framework 时需要注意什么呢?

 - Engine Framework 中不应该包含有接入 Runtime 的特化接口, 也就是说他的代码中不应该有直接调用 Runtime 接口的代码存在
 - 特化操作应该放在各种注册中, Engine Framework 靠着注册增加自己解释 Runtime 的能力

## Engine Framework 需要哪些特性:

 - Fire.Class 基础 Class 定义
 - Fire.registerType ( runtimeType, descriptor ) 通过注册 runtime 的 type 为某个解释器, 使得这份 type 具备序列化, Inspector 中展示的能力, 默认的 mixin descriptor 是通过将一份 general object, 以其内部的关键字为索引, 在 descriptor 的指导下, 调用 runtime 的 api 给与 mixin target 身上赋值, 事件响应等操作.
 - Fire.registerHierarchy ( hierarchyDescript ) 通过注册 hieararchy 的 descript 来让 engine-framework 具备描述 runtime 的 scene graph 的能力
 - Fire.registerMixin ( runtimeType, mixinDescriptor ) 通过注册 mixin 的描述来让 engine-framework 懂得如何 mixin 一份 FireClass 到 runtimeType 中. 值得注意的是, 不同的 runtime 中, 他们 runtimeType 的 mixin 的关键字将会有些许变动, 比如: 有些 runtime 的 node 不支持 event, 那么 listeners 关键字: 在这些 runtime 中将会失效, 我们可以 warning user.
 - 序列化注册
 - Main Loop 注册

## 原来的 Core, Engine 去哪了

我们保留了 Core, Engine 中 Class, Serialize 以及 Loop 中的一些概念. 去掉了 entity-component 的概念. 实际上 Entity Component 属于 Runtime 层的行为, 所以在未来, Core Engine 中 entity-component, assets 等概念是放在 Runtime 层来实现, 并且, 通过注册 `Fire.registerMixin ( Fire.SomeComponent, MixinDesc.AddComponent )` 其中 MixinDesc.AddComopnent 是一份 mixinDescriptor, 他描述了如何将这份 component class mixin 到 entity 中, 他的内部实现, 也许像这样:

```javascript

ComponentMixinDescriptor = {
  mixin: function ( target, classDef ) {
    var comp = new Component();
    Fire.JS.mixin( comp, classDef.properites );
    target.addComponent ( comp );
  }
}

```

在设计 engine framework 时, 有一些优秀的 runtime 是我们需要时不时拿来参考的:

Mixin Based Runtime:

 - https://github.com/egret-labs
 - https://github.com/cocos2d/cocos2d-js
 - http://www.pixijs.com/
 - http://createjs.com/
 - https://github.com/photonstorm/phaser
 - http://threejs.org/

Entity Compnoent Based Rutime:

 - https://github.com/playcanvas/engine
 - https://github.com/BabylonJS/Babylon.js

**Comment by jareguo** [comment]
> Fire.registerHierarchy ( hierarchyDescript ) 通过注册 hieararchy 的 descript 来让 engine-framework 具备描述 runtime 的 scene graph 的能力

似乎不用注册，写一个公有方法就行了，例如：
```
var NodeOperator = Editor.getTypeOperator(cc.Node);
function __getChildren (node) {
    var name = NodeOperator.getName(node);
    var children = NodeOperator.getChildren(node);
    return {
        name: name,
        children: children.map(__getChildren)
    };
}
function takeHierarchySnapshot () {
    var root = cc.game.currentRuningScene;
    var children = NodeOperator.getChildren(node);
    return children.map(__getChildren);
}
```

**Comment by jareguo** [comment]
关于类型注册，具体一点的做法是：
```js
// 注册
Editor. registerType(cc.Node, MyOperator);
// 操作
var Operator = Editor.getOperator(theObject);
console.log(Operator.getName(theObject));
console.log(Operator.getChildren(theObject));
...
```
还有一种方法，你看看好不好。
```js
// 注册
var bindedOperator = {
    target: null,
    get name () { return this.target._ccName; },
    get children () { return this.target._ccChildren; },
};
Object.defineProperty(cc.Node.prototype, 'FB', {
    get: function () {
        bindedOperator.target = this;
        return bindedOperator;
    }
});
// 操作
console.log(theObject.FB.name);
console.log(theObject.FB.children);
```

**Comment by jwu** [comment]
- hierarchy 部分的解法很好.
 - 我倾向第一种, 对用户清晰. Polymer, Rect 和 Angular 也是这个策略, 通过 Polymer.dom 来操作 dom 树.

我倾向 Editor.getOperator 这句话简化一下, Editor.node(...). 至于 wrap 后的 operator, 可以考虑用第二种方法里的 name, children, 比较简单.

**Comment by jareguo** [comment]
用户脚本的定义方式，我觉得可以照样要求用户写 Fire.Class。这样满足用户的继承、property序列化需求的同时，不会增加额外的学习成本。

**Comment by jwu** [comment]
同意. 但 `behaviours: []` 部分, 还请只允许用 pure object. 这个是为了降低复杂度.

**Comment by jareguo** [comment]
明白。

**Comment by jareguo** [comment]
cocos 有些对象的反序列化需要异步加载，所以没办法直接在一个 pass 里把场景重建出来。
我的想法是加载场景时，先用原有的反序列化机制把 wrapper 全部反序列化出来，然后调用所有 wrapper 的 serializeAsync 方法。serializeAsync 会读取 wrapper 上的 properties，来加载所依赖的资源，并且创建 node。
node 创建以后，执行 mixin 操作（挂用户脚本），然后还原 mixin 上去的 properties。
等 node 全部创建好以后，还原 node 之间的父子关系。

这些步骤比较复杂，并且有几个操作很难实现，一是在 mixin 脚本里关联 asset (因为没有 Asset 了)，二是在 mixin 脚本里关联其它 Node 对象（将来可以再加一个 pass）。

**Comment by jareguo** [comment]
Main Loop 注册不需要吧？

**Comment by jwu** [comment]
应该还是可以让用户注册自己的 main-loop 吧 ?

**Comment by jareguo** [comment]
用户的引擎自己就有一套main loop了，不知道注册了要干嘛？

**Comment by jwu** [comment]
有的引擎比如 pixi, three.js 他们的 main-loop 是交给用户自己处理, 对于这些引擎的用户, main-loop 归还给他们控制是他们的期望.

**Comment by jareguo** [comment]
用户可以直接控制 Main Loop，不需要我们归还啊？

**Comment by jareguo** [comment]
序列化 和 MainLoop 注册已加上
