### ISSUE TITLE
统一 callback ( err, ... ) 中的 error 为 Error 而不是 string

### ISSUE THREAD

**Issue by jwu** [fireball-x/engine-framework#15]
目前我发现 runtime, engine-framework 的报错信息处理都是采用直接 string 的形式, 这样的出错信息, 不仅无法通过 err.stack 获得报错定位, 而且不标准. 

直接 string error 的形式需要杜绝的原因有两个:

1. 用户可能认为那是一个返回值为 string 的 callback 而不是一个 error.
2. 出错位置无法得到追踪 (err.stack) 

请检查 runtime, engine-framework 中这些不标准的 callback error 信息, 并予以纠正.

@jareguo @2youyouo2

**Comment by jwu** [comment]
some code relate with this issue: https://github.com/fireball-packages/scene/blob/master/panel/webview/ipc.js#L46

**Comment by jareguo** [comment]
@2youyouo2 engine-framework 这边我改好了，runtime 那边你自己改一下
