### ISSUE TITLE
Fire.node parent 和 parentNode 的困惑

### ISSUE THREAD

**Issue by jwu** [fireball-x/engine-framework#19]
@jareguo @2youyouo2 

我在使用 Fire.node 添加节点的时候, 发现这样的疑惑:

如果我创建的节点要添加到场景中, 我需要这么操作

```javascript
var fireNode = Fire.node( aNewCCNode );
fireNode.parent = Fire.engine.getCurrentScene();
```

但如果我要添加到某个节点之下的时候, 我需要这么操作:

```javascript
var fireNode = Fire.node( aNewCCNode );
fireNode.parentNode = Fire.engine.getInstanceById(id);
```

我这里比较困惑的是:

1. 什么时候用 parent, 什么时候用 parentNode? 
2. Fire.engine.getCurrentScene() 是 Fire 的 api 还是 cc 的 api? 如果是 Fire 的 API 返回的应该是 Fire.node 吧?

**Comment by jwu** [comment]
我大概知道我误操作的原因了, 主要是因为 `Fire.engine.getInstanceById` 返回的是 ccNode 而 `Fire.engine.getCurrentScene` 返回的是 Fire.node. 这里我想我们应该有一个统一的标准, 比如 Fire 的 API 返回的一定是 Fire.node 而不应该返回 nativeNode

此外,  parent 和  parentNode 也让人非常容易混淆. 如果我们确定 parent 为 Fire.node, 那么我觉得在接口设计上应该杜绝 parentNode, 且不鼓励用户在 Fire.node 上和 nativeNode 做交互.

**Comment by jareguo** [comment]
你只要记住这两句话：
所有以 Node 结尾的 API，返回的就是 node，否则返回的是 wrapper。
Instance 和 ID 都是 Node 才有的东西，wrapper 没有这两个概念。

**Comment by jareguo** [comment]
另外：
所有带 Node 的 API，都是给 runtime 用的。
Editor 用的 Fire 上的接口，都是不带 Node 的。

**Comment by jwu** [comment]
我们统一一下 API 接口命名规范, 返回 runtime 相关的函数, 请已 `runtime` 开头
