### ISSUE TITLE
调整代码结构

### ISSUE THREAD

**Issue by jareguo** [fireball-x/engine-framework#2]
这次的 engine-framework 使用免编译的加载流程，因此代码里面需要编译的部分都要进行修改。
包括：
- 移除 preprocess 宏
- 将 gulp concat 的代码按顺序 require
- 使用 node.js 的方式组织目录结构，建立 index.js 文件
- 内部直接访问的局部变量，改成 export + require

**Comment by jwu** [comment]
请在做之前先在 目前的 fireball (dev branch) 里的 package-studio 下测试一下这种流程是否能够在 electron 中跑起来. 因为我怀疑 require 会有路径问题. 所以书写上是否需要特化?

就我 editor-framework 的 page-level require 的书写经验, 我需要做 

```javascript
var Foobar = Editor.require('editor-framework://foo/bar/foobar');
```
