### ISSUE TITLE
建立测试用例流程

### ISSUE THREAD

**Issue by jareguo** [fireball-x/engine-framework#3]
RT

**Comment by jwu** [comment]
能否考虑和 editor, editor-framework 这里的测试流程一致, 采用 mocha + chai + sinon

**Comment by jwu** [comment]
关于 mocha 测试报告和 qunit 对比有不足的地方请在这里指出, 我看看是否有方法做好.

**Comment by jareguo** [comment]
测试用例改起来太费力了，现在先不考虑整合测试用例到 editor 里面，反正是单元测试而已。
