### ISSUE TITLE
实现场景保存功能

### ISSUE THREAD

**Issue by jareguo** [fireball-x/engine-framework#8]
cocos 有些对象的反序列化需要异步加载，所以没办法直接在一个 pass 里把场景重建出来。
我的想法是依次：
- 用 AssetLibrary 把 wrapper 连带 properties 上关联的 asset 全部加载进来
- 调用所有 wrapper 的 createNode (async) 方法
    - 在创建好的 node 上执行 mixin 操作（挂用户脚本）
    - 还原 mixin 上去的 properties
- 还原 node 之间的父子关系

问题：
- mixin 挂上去的 properties，要序列化在什么地方？  
整个场景的序列化的时候，采用手工序列化的形式，将 wrapper 和 mixin 分批保存。
- mixin 的 properties 和其它对象的关联怎么保存？
整个场景树成批保存，这样能保留 mixin 和其它对象之间的关联，但是序列化时要将 mixin 后的 primitive node 当成 fire class 解析。加载的时候，需要先用 wrapper 生成整个场景树。

**Comment by jareguo** [comment]
@2youyouo2 你觉得这个步骤可行吗？cocos 有没有现成的 api 可以让我们保存/还原场景？

**Comment by 2youyouo2** [comment]
1. cocos 像这种场景序列化都得自己写了
2. 我刚才看了spine是支持用 file来创建的，
我这前创建spine的方法：
```javascript
var json  = this._file;
var atlas = this._file.replace('.json', '') + '.atlas';
var spine = new sp.SkeletonAnimation(json, atlas);
```

**Comment by 2youyouo2** [comment]
可以直接创建是因为反序列化对象之前有预加载资源这一步，
预加载完成后才开始反序列化对象。

**Comment by jareguo** [comment]
（spine 支持用 url 创建，但需要预加载资源。）

如果要结合 cocos lite 之前的做法，那么就可以去掉异步操作：
- 读取场景的资源预加载列表，预加载所有资源
- 用 AssetLibrary 把 wrapper 连带 properties 上关联的 asset 全部加载进来
- 从根节点开始依次调用所有子 wrapper 的 createNode (sync) 方法
    - 设置 node 父子关系
    - 在 node 上执行 mixin 操作（挂用户脚本）
    - 还原 mixin 上去的 properties

**Comment by jareguo** [comment]
已完成，但是如果 mixin 的脚本将 runtime node 直接序列化会出错，这个问题还不太好解决。
